
package com.upem.converterServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConverterDAOImplService", targetNamespace = "http://dao.converter.upem.com/", wsdlLocation = "http://localhost:1235/convertirservice?wsdl")
public class ConverterDAOImplService
    extends Service
{

    private final static URL CONVERTERDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERTERDAOIMPLSERVICE_EXCEPTION;
    private final static QName CONVERTERDAOIMPLSERVICE_QNAME = new QName("http://dao.converter.upem.com/", "ConverterDAOImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1235/convertirservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTERDAOIMPLSERVICE_WSDL_LOCATION = url;
        CONVERTERDAOIMPLSERVICE_EXCEPTION = e;
    }

    public ConverterDAOImplService() {
        super(__getWsdlLocation(), CONVERTERDAOIMPLSERVICE_QNAME);
    }

    public ConverterDAOImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTERDAOIMPLSERVICE_QNAME, features);
    }

    public ConverterDAOImplService(URL wsdlLocation) {
        super(wsdlLocation, CONVERTERDAOIMPLSERVICE_QNAME);
    }

    public ConverterDAOImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTERDAOIMPLSERVICE_QNAME, features);
    }

    public ConverterDAOImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConverterDAOImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConverterDAOImpl
     */
    @WebEndpoint(name = "ConverterDAOImplPort")
    public ConverterDAOImpl getConverterDAOImplPort() {
        return super.getPort(new QName("http://dao.converter.upem.com/", "ConverterDAOImplPort"), ConverterDAOImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConverterDAOImpl
     */
    @WebEndpoint(name = "ConverterDAOImplPort")
    public ConverterDAOImpl getConverterDAOImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.converter.upem.com/", "ConverterDAOImplPort"), ConverterDAOImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTERDAOIMPLSERVICE_EXCEPTION!= null) {
            throw CONVERTERDAOIMPLSERVICE_EXCEPTION;
        }
        return CONVERTERDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
