
package com.upem.converterServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConverterDAOImpl", targetNamespace = "http://dao.converter.upem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConverterDAOImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirPoundToDollar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirPoundToDollar", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirPoundToDollar")
    @ResponseWrapper(localName = "ConvertirPoundToDollarResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirPoundToDollarResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirPoundToDollarRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirPoundToDollarResponse")
    public double convertirPoundToDollar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirEURToDollar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirEURToDollar", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirEURToDollar")
    @ResponseWrapper(localName = "ConvertirEURToDollarResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirEURToDollarResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirEURToDollarRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirEURToDollarResponse")
    public double convertirEURToDollar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirEURToPound")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirEURToPound", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirEURToPound")
    @ResponseWrapper(localName = "ConvertirEURToPoundResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirEURToPoundResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirEURToPoundRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirEURToPoundResponse")
    public double convertirEURToPound(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirPoundToEUR")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirPoundToEUR", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirPoundToEUR")
    @ResponseWrapper(localName = "ConvertirPoundToEURResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirPoundToEURResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirPoundToEURRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirPoundToEURResponse")
    public double convertirPoundToEUR(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirDollarToPound")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirDollarToPound", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirDollarToPound")
    @ResponseWrapper(localName = "ConvertirDollarToPoundResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirDollarToPoundResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirDollarToPoundRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirDollarToPoundResponse")
    public double convertirDollarToPound(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertirDollarToEur")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertirDollarToEur", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirDollarToEur")
    @ResponseWrapper(localName = "ConvertirDollarToEurResponse", targetNamespace = "http://dao.converter.upem.com/", className = "com.upem.converterServices.ConvertirDollarToEurResponse")
    @Action(input = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirDollarToEurRequest", output = "http://dao.converter.upem.com/ConverterDAOImpl/ConvertirDollarToEurResponse")
    public double convertirDollarToEur(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
