
package com.upem.bankservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankDAOImplService", targetNamespace = "http://dao.bank.upem.com/", wsdlLocation = "http://localhost:1234/bankservice?wsdl")
public class BankDAOImplService
    extends Service
{

    private final static URL BANKDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKDAOIMPLSERVICE_EXCEPTION;
    private final static QName BANKDAOIMPLSERVICE_QNAME = new QName("http://dao.bank.upem.com/", "BankDAOImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/bankservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKDAOIMPLSERVICE_WSDL_LOCATION = url;
        BANKDAOIMPLSERVICE_EXCEPTION = e;
    }

    public BankDAOImplService() {
        super(__getWsdlLocation(), BANKDAOIMPLSERVICE_QNAME);
    }

    public BankDAOImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKDAOIMPLSERVICE_QNAME, features);
    }

    public BankDAOImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKDAOIMPLSERVICE_QNAME);
    }

    public BankDAOImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKDAOIMPLSERVICE_QNAME, features);
    }

    public BankDAOImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankDAOImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankDAOImpl
     */
    @WebEndpoint(name = "BankDAOImplPort")
    public BankDAOImpl getBankDAOImplPort() {
        return super.getPort(new QName("http://dao.bank.upem.com/", "BankDAOImplPort"), BankDAOImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankDAOImpl
     */
    @WebEndpoint(name = "BankDAOImplPort")
    public BankDAOImpl getBankDAOImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.bank.upem.com/", "BankDAOImplPort"), BankDAOImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKDAOIMPLSERVICE_EXCEPTION!= null) {
            throw BANKDAOIMPLSERVICE_EXCEPTION;
        }
        return BANKDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
