
package com.upem.sellingservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SellingDAO", targetNamespace = "http://dao.selling.upem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SellingDAO {


    /**
     * 
     * @return
     *     returns java.util.List<com.upem.sellingservices.BookWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBookForSelling", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllBookForSelling")
    @ResponseWrapper(localName = "getAllBookForSellingResponse", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllBookForSellingResponse")
    @Action(input = "http://dao.selling.upem.com/SellingDAO/getAllBookForSellingRequest", output = "http://dao.selling.upem.com/SellingDAO/getAllBookForSellingResponse")
    public List<BookWS> getAllBookForSelling();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.upem.sellingservices.BookWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBorrowedBooks", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllBorrowedBooks")
    @ResponseWrapper(localName = "getAllBorrowedBooksResponse", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllBorrowedBooksResponse")
    @Action(input = "http://dao.selling.upem.com/SellingDAO/getAllBorrowedBooksRequest", output = "http://dao.selling.upem.com/SellingDAO/getAllBorrowedBooksResponse")
    public List<BookWS> getAllBorrowedBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.upem.sellingservices.UserWS>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetAllUsersResponse")
    @Action(input = "http://dao.selling.upem.com/SellingDAO/getAllUsersRequest", output = "http://dao.selling.upem.com/SellingDAO/getAllUsersResponse")
    public List<UserWS> getAllUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.AddBookResponse")
    @Action(input = "http://dao.selling.upem.com/SellingDAO/addBookRequest", output = "http://dao.selling.upem.com/SellingDAO/addBookResponse")
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        BookWS arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.upem.sellingservices.BookWS
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByISBN", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetBookByISBN")
    @ResponseWrapper(localName = "getBookByISBNResponse", targetNamespace = "http://dao.selling.upem.com/", className = "com.upem.sellingservices.GetBookByISBNResponse")
    @Action(input = "http://dao.selling.upem.com/SellingDAO/getBookByISBNRequest", output = "http://dao.selling.upem.com/SellingDAO/getBookByISBNResponse")
    public BookWS getBookByISBN(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
