
package com.upem.sellingservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SellingDAOService", targetNamespace = "http://dao.selling.upem.com/", wsdlLocation = "http://localhost:1478/sellingserviceWS?wsdl")
public class SellingDAOService
    extends Service
{

    private final static URL SELLINGDAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SELLINGDAOSERVICE_EXCEPTION;
    private final static QName SELLINGDAOSERVICE_QNAME = new QName("http://dao.selling.upem.com/", "SellingDAOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1478/sellingserviceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELLINGDAOSERVICE_WSDL_LOCATION = url;
        SELLINGDAOSERVICE_EXCEPTION = e;
    }

    public SellingDAOService() {
        super(__getWsdlLocation(), SELLINGDAOSERVICE_QNAME);
    }

    public SellingDAOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELLINGDAOSERVICE_QNAME, features);
    }

    public SellingDAOService(URL wsdlLocation) {
        super(wsdlLocation, SELLINGDAOSERVICE_QNAME);
    }

    public SellingDAOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELLINGDAOSERVICE_QNAME, features);
    }

    public SellingDAOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SellingDAOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SellingDAO
     */
    @WebEndpoint(name = "SellingDAOPort")
    public SellingDAO getSellingDAOPort() {
        return super.getPort(new QName("http://dao.selling.upem.com/", "SellingDAOPort"), SellingDAO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellingDAO
     */
    @WebEndpoint(name = "SellingDAOPort")
    public SellingDAO getSellingDAOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.selling.upem.com/", "SellingDAOPort"), SellingDAO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELLINGDAOSERVICE_EXCEPTION!= null) {
            throw SELLINGDAOSERVICE_EXCEPTION;
        }
        return SELLINGDAOSERVICE_WSDL_LOCATION;
    }

}
